### ISSUE TITLE
Failed to start ByteSafe

### ISSUE THREAD

**Issue by wonhee0410** [bitfront-se/bytesafe-ce#3]
Dear All,

I have installed Bytesafe Docker and using my company proxy, but when I start it, it shows the error bellow.
So are there any solutions for this ? Thank you.

`bytesafe-bytesafe-ce-1  | time="2023-06-13T02:14:20Z" level=fatal msg="failed to load vulnerabilities" error="http.Get: Get \"https://advisories.bytesafe.dev/vulndb.json.zst\": tls: failed to verify certificate: x509: certificate signed by unknown authority" pkg=bytesafe-ce`

**Comment by wallrat** [comment]
Hi,

so if I understand correctly, you are running behind proxy that responds with an internal, _untrusted_ cert for `https://advisories.bytesafe.dev` ?

The docker container `bytesafe/bytesafe-ce:latest` contains CA certs under `/etc/ssl/certs/ca-certificates.crt`, so you can replace that with a file that contains your company's CA.

If you are using the docker-compose.yml, you can just add a volume that replaces that file. Something like:

```yaml
services:
  bytesafe-ce:
    image: bytesafe/bytesafe-ce:latest
    restart: "no"
    volumes:
      -  company-trusted-certs.crt:/etc/ssl/certs/ca-certificates.crt
      - "bytesafe-blob-data:/var/lib/bytesafe"
      - "bytesafe-tmp:/tmp"
    ports:
      - "8081:8081"
```

**Comment by wonhee0410** [comment]
> 

Yeah, that's correct.

I'm using Redhat and the ca-certificates.crt in /etc/ssl/certs/ is not found.

**Comment by wonhee0410** [comment]
`All this assuming the the host running docker have the necessary CA installed of course, easy to check with curl https://advisories.bytesafe.dev/vulndb.json.zst.`

Thanks for your explanation !

A dump question, the curl command show with error (I have installed my company certificate in this directory 
/etc/pki/ca-trust/source/anchors/). Could you please suggest the way how to fix it ? Thank you.
```
curl -v https://advisories.bytesafe.dev/vulndb.json.zst
*   Trying 13.225.103.85...
* TCP_NODELAY set
* Connected to advisories.bytesafe.dev (13.225.103.85) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* error setting certificate verify locations, continuing anyway:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to advisories.bytesafe.dev:443 
* Closing connection 0
curl: (35) OpenSSL SSL_connect: SSL_ERROR_SYSCALL in connection to advisories.bytesafe.dev:443 
```

**Comment by wallrat** [comment]
If I remember correctly you should run **update-ca-trust** tool after installing the cert to update the CA bundle in /etc/pki/tls/certs/ca-bundle.crt.

**Comment by wonhee0410** [comment]
After fixing this above problem, now the command `curl https://advisories.bytesafe.dev/vulndb.json.zst` runs successfully.

I have updated the docker-compose file like this:
```
services:
  bytesafe-ce:
    image: bytesafe/bytesafe-ce:latest
    restart: "no"
    volumes:
      - "/etc/pki/tls/certs:/etc/ssl/certs"
      - "bytesafe-blob-data:/var/lib/bytesafe"
      - "bytesafe-tmp:/tmp"
    ports:
      - "8081:8081"
```

But it not works, docker-compose up shows the same error, it's strange:
`bytesafe-bytesafe-ce-1  | time="2023-06-14T04:23:52Z" level=fatal msg="failed to load vulnerabilities" error="http.Get: Get \"https://advisories.bytesafe.dev/vulndb.json.zst\": tls: failed to verify certificate: x509: certificate signed by unknown authority" pkg=bytesafe-ce`
